(* =========================================================================
   WebAssembly Specification - Auto-generated from reference interpreter

   DO NOT EDIT MANUALLY - Generated by spec-sync tool
   Source: WebAssembly/spec interpreter/syntax/{types.ml, ast.ml}

   To regenerate:
     bazel run //tools/spec-sync -- --spec-dir <path> --output <output.v>
   ========================================================================= *)

From Stdlib Require Import List ZArith Bool.
Import ListNotations.

(* Placeholder for strings - using nat for simplicity *)
Definition wasm_string := nat.

(* half *)
Inductive Half : Type :=
  | Half_Low
  | Half_High
.

(* iunop *)
Inductive Iunop : Type :=
  | Iunop_Abs
  | Iunop_Neg
  | Iunop_Popcnt
.

(* sx *)
Inductive Sx : Type :=
  | Sx_Pack
  | Sx_S
  | Sx_U
.

(* fbinop *)
Inductive Fbinop : Type :=
  | Fbinop_Add
  | Fbinop_Sub
  | Fbinop_Mul
  | Fbinop_Div
  | Fbinop_Min
  | Fbinop_Max
  | Fbinop_Pmin
  | Fbinop_Pmax
  | Fbinop_RelaxedMin
  | Fbinop_RelaxedMax
.

(* binop *)
Inductive Binop : Type :=
  | Binop_Add
  | Binop_Sub
  | Binop_Mul
  | Binop_Div
  | Binop_Min
  | Binop_Max
  | Binop_CopySign
.

(* typeidx *)
Definition Wasm_typeidx := nat.

(* typeuse *)
Inductive Wasm_typeuse : Type :=
  | Wasm_typeuse_Idx (arg0 : Wasm_typeidx)
  | Wasm_typeuse_Rec (arg0 : nat)
  | Wasm_typeuse_Def (arg0 : Defwasm_type)
.

(* tagtype *)
Inductive Tagwasm_type : Type :=
  | Tagwasm_type_TagT (arg0 : Wasm_typeuse)
.

(* testop *)
Definition Testop := Eqz.

(* ibitmaskop *)
Definition Ibitmaskop := Bitmask.

(* mut *)
Inductive Mut : Type :=
  | Mut_Cons
  | Mut_Var
.

(* globaltype *)
Inductive Globalwasm_type : Type :=
  | Globalwasm_type_GlobalT (arg0 : Mut) (arg1 : Valwasm_type)
.

(* frelop *)
Inductive Frelop : Type :=
  | Frelop_Eq
  | Frelop_Ne
  | Frelop_Lt
  | Frelop_Le
  | Frelop_Gt
  | Frelop_Ge
.

(* vtestop *)
Definition Vtestop := AnyTrue.

(* unop *)
Inductive Unop : Type :=
  | Unop_Neg
  | Unop_Abs
  | Unop_Ceil
  | Unop_Floor
  | Unop_Trunc
  | Unop_Nearest
  | Unop_Sqrt
.

(* localidx *)
Definition Localidx := nat.

(* externop *)
Inductive Externop : Type :=
  | Externop_Internalize
  | Externop_Externalize
.

(* nreplaceop *)
Inductive Nreplaceop : Type :=
  | Nreplaceop_Replace (arg0 : nat)
.

(* iternop *)
Inductive Iternop : Type :=
  | Iternop_RelaxedLaneselect
  | Iternop_RelaxedDotAddS
.

(* funop *)
Inductive Funop : Type :=
  | Funop_Abs
  | Funop_Neg
  | Funop_Sqrt
  | Funop_Ceil
  | Funop_Floor
  | Funop_Trunc
  | Funop_Nearest
.

(* nsplatop *)
Definition Nsplatop := Splat.

(* limits *)
Record Limits : Type := mkLimits {
  Limits_min : nat;
  Limits_max : option (nat);
}.

(* tabletype *)
Inductive Tablewasm_type : Type :=
  | Tablewasm_type_TableT (arg0 : Addrwasm_type) (arg1 : Limits) (arg2 : Refwasm_type)
.

(* memorytype *)
Inductive Memorywasm_type : Type :=
  | Memorywasm_type_MemoryT (arg0 : Addrwasm_type) (arg1 : Limits)
.

(* externtype *)
Inductive Externwasm_type : Type :=
  | Externwasm_type_ExternTagT (arg0 : Tagwasm_type)
  | Externwasm_type_ExternGlobalT (arg0 : Globalwasm_type)
  | Externwasm_type_ExternMemoryT (arg0 : Memorywasm_type)
  | Externwasm_type_ExternTableT (arg0 : Tablewasm_type)
  | Externwasm_type_ExternFuncT (arg0 : Wasm_typeuse)
.

(* importtype *)
Inductive Importwasm_type : Type :=
  | Importwasm_type_ImportT (arg0 : Name) (arg1 : Name) (arg2 : Externwasm_type)
.

(* exporttype *)
Inductive Exportwasm_type : Type :=
  | Exportwasm_type_ExportT (arg0 : Name) (arg1 : Externwasm_type)
.

(* init *)
Inductive Init : Type :=
  | Init_Set
  | Init_Unset
.

(* localtype *)
Inductive Localwasm_type : Type :=
  | Localwasm_type_LocalT (arg0 : Init) (arg1 : Valwasm_type)
.

(* blocktype *)
Inductive Blockwasm_type : Type :=
  | Blockwasm_type_VarBlockType (arg0 : Idx)
  | Blockwasm_type_ValBlockType (arg0 : option (Valwasm_type))
.

(* initop *)
Inductive Initop : Type :=
  | Initop_Explicit
  | Initop_Implicit
.

(* relop *)
Inductive Relop : Type :=
  | Relop_Eq
  | Relop_Ne
  | Relop_Lt
  | Relop_Gt
  | Relop_Le
  | Relop_Ge
.

(* final *)
Inductive Final : Type :=
  | Final_NoFinal
  | Final_Final
.

(* vternop *)
Definition Vternop := Bitselect.

(* vbinop *)
Inductive Vbinop : Type :=
  | Vbinop_And
  | Vbinop_Or
  | Vbinop_Xor
  | Vbinop_AndNot
.

(* sx *)
Inductive Sx : Type :=
  | Sx_Pack
  | Sx_S
  | Sx_U
.

(* ishiftop *)
Inductive Ishiftop : Type :=
  | Ishiftop_Shl
  | Ishiftop_Shr (arg0 : Sx)
.

(* fcvtop *)
Inductive Fcvtop : Type :=
  | Fcvtop_DemoteZeroF64x2
  | Fcvtop_PromoteLowF32x4
  | Fcvtop_ConvertI32x4 (arg0 : Sx)
.

(* icvtop *)
Inductive Icvtop : Type :=
  | Icvtop_Extend (arg0 : Half) (arg1 : Sx)
  | Icvtop_ExtAddPairwise (arg0 : Sx)
  | Icvtop_TruncSatF32x4 (arg0 : Sx)
  | Icvtop_TruncSatZeroF64x2 (arg0 : Sx)
  | Icvtop_RelaxedTruncF32x4 (arg0 : Sx)
  | Icvtop_RelaxedTruncZeroF64x2 (arg0 : Sx)
.

(* irelop *)
Inductive Irelop : Type :=
  | Irelop_Eq
  | Irelop_Ne
  | Irelop_Lt (arg0 : Sx)
  | Irelop_Le (arg0 : Sx)
  | Irelop_Gt (arg0 : Sx)
  | Irelop_Ge (arg0 : Sx)
.

(* ibinop *)
Inductive Ibinop : Type :=
  | Ibinop_Add
  | Ibinop_Sub
  | Ibinop_Mul
  | Ibinop_Min (arg0 : Sx)
  | Ibinop_Max (arg0 : Sx)
  | Ibinop_AvgrU
  | Ibinop_AddSat (arg0 : Sx)
  | Ibinop_SubSat (arg0 : Sx)
  | Ibinop_DotS
  | Ibinop_Q15MulRSatS
  | Ibinop_ExtMul (arg0 : Half) (arg1 : Sx)
  | Ibinop_Swizzle
  | Ibinop_Shuffle (arg0 : list (nat))
  | Ibinop_Narrow (arg0 : Sx)
  | Ibinop_RelaxedSwizzle
  | Ibinop_RelaxedQ15MulRS
  | Ibinop_RelaxedDot
.

(* cvtop *)
Inductive Cvtop : Type :=
  | Cvtop_ConvertI32 (arg0 : Sx)
  | Cvtop_ConvertI64 (arg0 : Sx)
  | Cvtop_PromoteF32
  | Cvtop_DemoteF64
  | Cvtop_ReinterpretInt
.

(* cvtop *)
Inductive Cvtop : Type :=
  | Cvtop_ExtendI32 (arg0 : Sx)
  | Cvtop_WrapI64
  | Cvtop_TruncF32 (arg0 : Sx)
  | Cvtop_TruncF64 (arg0 : Sx)
  | Cvtop_TruncSatF32 (arg0 : Sx)
  | Cvtop_TruncSatF64 (arg0 : Sx)
  | Cvtop_ReinterpretFloat
.

(* relop *)
Inductive Relop : Type :=
  | Relop_Eq
  | Relop_Ne
  | Relop_Lt (arg0 : Sx)
  | Relop_Gt (arg0 : Sx)
  | Relop_Le (arg0 : Sx)
  | Relop_Ge (arg0 : Sx)
.

(* binop *)
Inductive Binop : Type :=
  | Binop_Add
  | Binop_Sub
  | Binop_Mul
  | Binop_Div (arg0 : Sx)
  | Binop_Rem (arg0 : Sx)
  | Binop_And
  | Binop_Or
  | Binop_Xor
  | Binop_Shl
  | Binop_Shr (arg0 : Sx)
  | Binop_Rotl
  | Binop_Rotr
.

(* vunop *)
Definition Vunop := Not.

(* itestop *)
Definition Itestop := AllTrue.

(* fternop *)
Inductive Fternop : Type :=
  | Fternop_RelaxedMadd
  | Fternop_RelaxedNmadd
.

(* null *)
Inductive Null : Type :=
  | Null_NoNull
  | Null_Null
.

(* unop *)
Inductive Unop : Type :=
  | Unop_Clz
  | Unop_Ctz
  | Unop_Popcnt
  | Unop_ExtendS (arg0 : Packsize)
.

(* End of auto-generated definitions *)
